// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:2c604869-2aed-4131-8f83-699862e98cd4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_sZUkzjXpH",
    "aws_user_pools_web_client_id": "4ttkr8fi0oon4c34p3rse4mrft",
    "oauth": {}
};


export default awsmobile;
