// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9fe6d2d8-d11e-48eb-9923-a11abcff4e19",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5rKrIPuqu",
    "aws_user_pools_web_client_id": "rvf4vrkvn2078h6nci21moumc",
    "oauth": {}
};


export default awsmobile;
